---
name: Development Environment

on:
  push:
    branches-ignore:
      - dependabot/**
    paths:
      - '.devcontainer/**'
      - '.github/workflows/dev-environment.yml'
  schedule:
    - cron: '0 1 * * 2'
  workflow_dispatch:

env:
  IMAGE_NAME: devcontainer
  CONTEXT: .devcontainer
  DOCKERFILE: Dockerfile

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    env:
      CHEF_LICENSE: accept-no-persist
      CONTAINER_NAME: system_under_test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.CONTEXT }}/${{ env.DOCKERFILE }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image WITHOUT pushing
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.CONTEXT }}/${{ env.DOCKERFILE }}
          build-args: |
            VERSION=${{ github.sha }}
            COMMIT_SHA=${{ github.sha }}
          platforms: linux/amd64
          push: false
          tags: local/${{ env.IMAGE_NAME }}:${{ github.sha }}

  sync-assets:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          version: 3.x
      - name: Run task to generate docs
        run: |
          export TASK_X_REMOTE_TASKFILES=1
          task sync:assets-from-github --yes
        shell: bash
      - name: Commit and push
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: 'ci: [Actions Bot] sync assets from sommerfeldio/.github'
